name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno:
    name: Deno Lint, Format, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno Dependencies
        run: deno cache main.ts

      - name: Lint Code
        run: deno lint

      - name: Check Formatting
        run: deno fmt --check

      - name: Run Tests
        run: deno test --allow-all
